# Generated by Django 4.2.7 on 2024-09-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_country_serviceline_vendor_customer_city_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='end_hour',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='start_hour',
            field=models.TimeField(default=None, null=True),
        ),
    ]
