# Generated by Django 4.2.7 on 2024-10-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
