# Generated by Django 4.2.7 on 2024-10-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_vendor_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='service_line',
        ),
        migrations.CreateModel(
            name='VendorServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceline')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
        ),
    ]
